import {
  anghami,
  basedash,
  bimi,
  chatbase,
  craiyon,
  dns,
  domain,
  elixir,
  fey,
  go,
  guruhotel,
  inbox,
  infiscal,
  ips,
  java,
  js,
  leap,
  mintlify,
  payload,
  php,
  python,
  rest,
  ruby,
  serverless,
  shepherd,
  smtp,
  suppress,
  tab1,
  tab2,
  tab3,
  tested,
  tracking,
  warnerbros,
} from '../assets';

export const navLinks = [
  { name: 'About', href: '#' },
  { name: 'Blog', href: '#' },
  { name: 'Customers', href: '#' },
  { name: 'Pricing', href: '#' },
  { name: 'Enterprise', href: '#' },
  { name: 'Changelog', href: '#' },
  { name: 'Docs', href: '#' },
];

export const companies = [
  { src: warnerbros },
  { src: leap },
  { src: fey },
  { src: anghami },
  { src: payload },
  { src: mintlify },
  { src: shepherd },
  { src: basedash },
  { src: guruhotel },
  { src: infiscal },
  { src: chatbase },
  { src: craiyon },
];

export const logos = [
  { name: 'Node.js', src: js },
  { name: 'Serverless', src: serverless },
  { name: 'Ruby', src: ruby },
  { name: 'Python', src: python },
  { name: 'PHP', src: php },
  { name: 'Go', src: go },
  { name: 'Java', src: java },
  { name: 'Elixir', src: elixir },
  { name: 'REST', src: rest },
  { name: 'SMTP', src: smtp },
];

export const folders = [
  {
    header: 'Proactive blocklist tracking',
    text: 'Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.',
    src: tracking,
  },
  {
    header: 'Faster Time to Inbox',
    text: 'Send emails from the region closest to your users.Reduce delivery latency with North American, South American, and European regions.',
    src: inbox,
  },
  {
    header: 'Build confidence with BIMI',
    text: 'Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media.',
    src: bimi,
  },
  {
    header: 'Managed Dedicated IPs',
    text: 'Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.',
    src: ips,
  },
  {
    header: 'Dynamic suppression list',
    text: 'Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.',
    src: suppress,
  },
  {
    header: 'IP and domain monitoring',
    text: 'Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.',
    src: domain,
  },
  {
    header: 'Verify DNS records',
    text: 'Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.',
    src: dns,
  },
  {
    header: 'Battle-tested infrastructure',
    text: `Rely on a platform of reputable IP's used by trustworthy senders with distributed workloads across different IP pools.`,
    src: tested,
  },
  {
    header: 'Prevent spoofing with DMARC.',
    text: 'Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email.',
    src: tested,
  },
];

export const tabs = [{ src: tab1 }, { src: tab2 }, { src: tab3 }];
